#!/usr/bin/env python3
"""
Market Close Routine — 15:00 EST / 18:00 Riyadh
EOD journaling + performance summary + Telegram notification
READ memory → JOURNAL → WRITE memory → NOTIFY
"""
import os, json, logging
from pathlib import Path
from datetime import datetime, date
import urllib.request
import anthropic
import alpaca_trade_api as tradeapi

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

ANTHROPIC_KEY  = os.environ.get("ANTHROPIC_API_KEY", "")
ALPACA_KEY     = os.environ.get("ALPACA_API_KEY", "")
ALPACA_SECRET  = os.environ.get("ALPACA_SECRET_KEY", "")
ALPACA_URL     = os.environ.get("ALPACA_BASE_URL", "https://paper-api.alpaca.markets")
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT  = os.environ.get("TELEGRAM_CHAT_ID", "")
MEMORY_DIR     = Path(__file__).parent.parent / "memory"

def read_memory():
    return {f.stem: f.read_text(encoding="utf-8") for f in MEMORY_DIR.glob("*.md")}

def write_memory(filename, content):
    (MEMORY_DIR / filename).write_text(content, encoding="utf-8")

def send_telegram(message):
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT:
        logger.warning("Telegram not configured"); return
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        data = json.dumps({"chat_id": TELEGRAM_CHAT, "text": message, "parse_mode": "Markdown"}).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=10)
        logger.info("Telegram sent ✅")
    except Exception as e:
        logger.error("Telegram failed: %s", e)

def run():
    logger.info("=== MARKET CLOSE ROUTINE | %s ===", datetime.now().strftime("%Y-%m-%d %H:%M"))

    memory = read_memory()
    api = tradeapi.REST(ALPACA_KEY, ALPACA_SECRET, ALPACA_URL)
    acct = api.get_account()
    equity = float(acct.equity)
    last_equity = float(acct.last_equity)
    day_pnl = equity - last_equity
    day_pnl_pct = (day_pnl / last_equity) * 100 if last_equity > 0 else 0

    try:
        positions = api.list_positions()
        pos_summary = "\n".join([
            f"- {p.symbol}: {p.qty}sh | Entry ${p.avg_entry_price} | P&L ${p.unrealized_pl} ({float(p.unrealized_plpc)*100:.1f}%)"
            for p in positions
        ]) or "No open positions"
    except:
        pos_summary = "Unable to fetch positions"

    client = anthropic.Anthropic(api_key=ANTHROPIC_KEY)

    prompt = f"""You are an autonomous trading agent completing the end-of-day journal.

MEMORY FILES:
{json.dumps({k: v[:500] for k, v in memory.items()}, indent=2)}

TODAY'S PERFORMANCE:
- Equity: ${equity:,.2f}
- Day P&L: ${day_pnl:+.2f} ({day_pnl_pct:+.2f}%)
- Open Positions: {pos_summary}

TASK: Write today's journal entry.
1. What happened today?
2. Did trades follow the strategy rules?
3. Lessons learned
4. Grade today: A/B/C/D/F
5. Plan for tomorrow

Return JSON:
{{
  "summary": "2-3 sentence day summary",
  "grade": "A",
  "lessons": "key lesson",
  "tomorrow_plan": "what to watch",
  "telegram_message": "short message for Telegram notification"
}}"""

    try:
        response = client.messages.create(
            model="claude-opus-4-7",
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}]
        )
        text = response.content[0].text.strip()
        result = json.loads(text[text.find("{"):text.rfind("}")+1])

        today = date.today().isoformat()

        # Update weekly review
        weekly = memory.get("weekly_review", "")
        weekly += f"\n\n## {today}\n"
        weekly += f"- Equity: ${equity:,.2f}\n"
        weekly += f"- Day P&L: ${day_pnl:+.2f} ({day_pnl_pct:+.2f}%)\n"
        weekly += f"- Grade: {result.get('grade','?')}\n"
        weekly += f"- Summary: {result.get('summary','')}\n"
        weekly += f"- Lessons: {result.get('lessons','')}\n"
        write_memory("weekly_review.md", weekly)

        # Telegram notification
        msg = f"""📊 *Daily Trading Report — {today}*

💰 Equity: ${equity:,.2f}
📈 Day P&L: ${day_pnl:+.2f} ({day_pnl_pct:+.2f}%)
🎯 Grade: {result.get('grade','?')}

📝 {result.get('summary','')}

🔮 Tomorrow: {result.get('tomorrow_plan','')}

_Auto-generated by Trading AI_"""

        send_telegram(msg)
        logger.info("EOD complete | Grade: %s | P&L: $%.2f", result.get('grade'), day_pnl)

    except Exception as e:
        logger.error("Market close routine failed: %s", e)

    logger.info("=== MARKET CLOSE COMPLETE ===")

if __name__ == "__main__":
    run()
