#!/usr/bin/env python3
"""
Weekly Review — Friday 16:00 EST / 19:00 Riyadh
Self-grade + strategy iteration + Telegram summary
READ memory → REVIEW → WRITE → NOTIFY
"""
import os, json, logging
from pathlib import Path
from datetime import datetime
import urllib.request
import anthropic

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

ANTHROPIC_KEY  = os.environ.get("ANTHROPIC_API_KEY", "")
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT  = os.environ.get("TELEGRAM_CHAT_ID", "")
MEMORY_DIR     = Path(__file__).parent.parent / "memory"

def read_memory():
    return {f.stem: f.read_text(encoding="utf-8") for f in MEMORY_DIR.glob("*.md")}

def write_memory(filename, content):
    (MEMORY_DIR / filename).write_text(content, encoding="utf-8")

def send_telegram(message):
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT:
        logger.warning("Telegram not configured"); return
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        data = json.dumps({"chat_id": TELEGRAM_CHAT, "text": message, "parse_mode": "Markdown"}).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
        urllib.request.urlopen(req, timeout=10)
        logger.info("Weekly Telegram sent ✅")
    except Exception as e:
        logger.error("Telegram failed: %s", e)

def run():
    logger.info("=== WEEKLY REVIEW | %s ===", datetime.now().strftime("%Y-%m-%d %H:%M"))

    memory = read_memory()
    client = anthropic.Anthropic(api_key=ANTHROPIC_KEY)

    prompt = f"""You are an autonomous trading agent doing your weekly self-review.

WEEKLY REVIEW FILE:
{memory.get('weekly_review', '')}

TRADE LOG:
{memory.get('trade_log', '')}

TRADING STRATEGY:
{memory.get('trading_strategy', '')}

TASK: Weekly performance review and strategy iteration.
1. Overall week grade (A-F)
2. What worked this week?
3. What failed?
4. Key lessons learned
5. Any strategy adjustments needed?
6. Next week focus

Return JSON:
{{
  "week_grade": "B",
  "what_worked": "summary",
  "what_failed": "summary",
  "lessons": "key lesson",
  "strategy_adjustments": "any changes or none",
  "next_week_focus": "what to watch",
  "telegram_message": "weekly summary for notification"
}}"""

    try:
        response = client.messages.create(
            model="claude-opus-4-8",
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}]
        )
        text = response.content[0].text.strip()
        result = json.loads(text[text.find("{"):text.rfind("}")+1])

        # Update weekly review
        week_summary = f"""
## Week ending {datetime.now().strftime('%Y-%m-%d')}
- Grade: {result.get('week_grade','?')}
- What worked: {result.get('what_worked','')}
- What failed: {result.get('what_failed','')}
- Lessons: {result.get('lessons','')}
- Strategy adjustments: {result.get('strategy_adjustments','')}
- Next week: {result.get('next_week_focus','')}
"""
        weekly = memory.get("weekly_review", "")
        write_memory("weekly_review.md", weekly + week_summary)

        # Telegram
        msg = f"""📅 *Weekly Trading Review*

🎯 Grade: {result.get('week_grade','?')}
✅ Worked: {result.get('what_worked','')}
❌ Failed: {result.get('what_failed','')}
💡 Lesson: {result.get('lessons','')}
🔮 Next week: {result.get('next_week_focus','')}

_Auto-generated by Trading AI_"""

        send_telegram(msg)
        logger.info("Weekly review complete | Grade: %s", result.get('week_grade'))

    except Exception as e:
        logger.error("Weekly review failed: %s", e)

if __name__ == "__main__":
    run()
